services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.5.0
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
    env_file:
      - .env
    environment:
      - DEBUG=0
      - PERSISTENCE=0
      - SERVICES=secretsmanager,ssm,events
      - SECRETS_FILENAME=secrets.env
      - PARAMS_FILENAME=params.env
    volumes:
      - localstack-volume:/var/lib/localstack
      - ./etc/localstack:/etc/localstack/init/ready.d
      - ./env:/var/lib/localstack/state
    networks:
      - localstack-network

  builder:
    image: gradle:8.14.2-jdk21-ubi-minimal
    container_name: ${SPRING_APPLICATION_NAME}-gradle-builder
    working_dir: /app
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    command: gradle bootJar
    networks:
      - localstack-network

  app:
    image: eclipse-temurin:21-jdk-jammy
    container_name: ${SPRING_APPLICATION_NAME}-spring
    depends_on:
      builder:
        condition: service_completed_successfully
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./build/libs:/app
    ports:
      - "$SERVER_PORT:$SERVER_PORT"
    command: java -jar ${SPRING_APPLICATION_NAME}.jar
    networks:
      - localstack-network

volumes:
  gradle-cache:
  localstack-volume:

networks:
  localstack-network:
#    driver: bridge
