spring:
  application:
    name: hello-app
  config:
    import[0]: aws-secretsmanager:/secret/${spring.application.name}
    import[1]: aws-parameterstore:/config/${spring.application.name}/
  cloud:
    aws:
      endpoint: https://localhost.localstack.cloud:4566
      region:
        static: us-east-1